name: build nodejs

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * 1"
    push:
      branches:
        - main
      paths:
      - nodejs/**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  push:
    name: "nodejs:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write
      
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 12
          - 14
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./nodejs
          file: ./nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/gameservershub-llc/nodejs:${{ matrix.tag }}
